### ISSUE TITLE
Convertion issues

### ISSUE THREAD

**Issue by imyelmo** [GNS3/gns3-converter#6]
I'm having conversion issues from 0.8.7 version. Do you know how could I figure out what it is going on? I asked the same on other repository but I think this is the right place. Thanks in advance.

**Comment by julien-duponchelle** [comment]
@jean-christophe-manciot is right in order to help you I suggest you open a new issue with details:
- the topology
- screenshot before conversion
- screenshot after conversion

**Comment by imyelmo** [comment]
I have opened an issue on: https://github.com/GNS3/gns3-gui/issues/1578
I have used the GUI to generate all the related information with the issue but I don't know if I should put it here under gns3-converter.

**Comment by julien-duponchelle** [comment]
The problem is a gns3 gui issue not a gns3 converter issue.
