### ISSUE TITLE
Why does gns3-converter ship with pbr & setuptools instead of specifying them inside requirements.txt?

### ISSUE THREAD

**Issue by jean-christophe-manciot** [GNS3/gns3-converter#7]
This creates:
- confusion
- clashes with other python packages such as python3-pip which ships with "/usr/local/lib/python3.5/dist-packages/pbr/__pycache__/__init__.cpython-35.pyc" for instance.

I suggest to update requirements.txt with:
```
configobj>=5.0.6
pbr>=<your call>
setuptools>=<your call>
```

**Comment by julien-duponchelle** [comment]
Sorry but I don't see where we have references to pbr

**Comment by jean-christophe-manciot** [comment]
I am unable to reproduce the issue.
